core/urls.py
from django.urls import path
from .views import index, product_list, categories_list, category_product_list_view
from .views import index, product_list, categories_list, vendor_list, vendor_detail, product_detail
from django.conf.urls.static import static
from django.conf import settings
app_name = 'core'

urlpatterns = [
    path('', index, name="index"),
    path('products/', product_list, name="product_list"),
    path('products/<pid>/', product_detail, name="product_detail"),

    path('categories/', categories_list, name="categories_list"),
    path('categories/<str:cit>/', category_product_list_view, name="category_product_list"),

    path('vendors/', vendor_list, name="vendor_list"),
    path('vendors/<vid>/', vendor_detail, name="vendor_detail"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('authentication.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

core/models.py
from django.db import models
from django.urls import reverse
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from authentication.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

STATUS_CHOICE = (
    ('process', 'В процесе'),
    ('shipped', 'Отправленный'),
    ('delivered', 'Доставленный'),
)

STATUS = (
    ('draft', 'В черновике'),
    ('disabled', 'Откленен'),
    ('rejected', 'Отменен'),
    ('in_review', 'На Расмотрении'),
    ('published', 'Опубликованно'),
)

RATING = (
    (1, '★☆☆☆☆'),
    (2, '★★☆☆☆'),
    (3, '★★★☆☆'),
    (4, '★★★★☆'),
    (5, '★★★★★'),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Category(models.Model):
    cit = ShortUUIDField(unique=True, length=10, max_length=20, prefix='cat', verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="Название")
    image = models.ImageField(upload_to='category', verbose_name="Картинка", default="category.jpg")

    def get_absolute_url(self):
        return reverse('category_product_list', kwargs={'cit': self.cit})

    class Meta:
        verbose_name = "Катогоия"
        verbose_name_plural = "Категории"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=20, prefix='ven', verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="Имя")
    address = models.CharField(max_length=100, verbose_name="Адрес")
    contact = models.CharField(max_length=100, verbose_name="Контакты")
    chat_resp_time = models.CharField(max_length=100, verbose_name="Время для чата")
    shipping_on_time = models.CharField(max_length=100, verbose_name="Время доставки")
    authentic_rating = models.CharField(max_length=100, verbose_name="Подлинный рейтинг")
    days_return = models.CharField(max_length=100, verbose_name="Дата возврата")
    warranty_period = models.CharField(max_length=100, verbose_name="Гарантийный период")
    image = models.ImageField(upload_to=user_directory_path, verbose_name="Картинка", default="vendor.jpg")
    cover_image = models.ImageField(upload_to=user_directory_path, verbose_name="Изображение обложки", default="cover_product.jpg")
    description = models.TextField(null=True, blank=True, verbose_name="Описание")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Пользователь")

    class Meta:
        verbose_name = "Поставщик"
        verbose_name_plural = "Поставщики"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Tag(models.Model):
    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="Имя")
    description = RichTextUploadingField(null=True, blank=True, verbose_name="Описание")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Пользователь")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name="Категория", related_name='category')
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, verbose_name="Поставщик", default=None, related_name='products')
    image = models.ImageField(upload_to=user_directory_path, verbose_name="Картинка", default="cover_product.jpg")
    price = models.DecimalField(max_digits=9999999999, decimal_places=2, verbose_name='Цена')
    old_price = models.DecimalField(max_digits=9999999999, decimal_places=2, verbose_name='Старая цена')
    specifications = RichTextUploadingField(null=True, blank=True, verbose_name='Характеристики')
    tags = TaggableManager(verbose_name='Теги')
    product_status = models.CharField(choices=STATUS, max_length=10, default='in_review',
                                      verbose_name='Статус продукта')

    type = models.CharField(max_length=100, verbose_name="Тип продукта", null=True, blank=True)
    life = models.DateField(verbose_name="Срок годности", null=True, blank=True)
    status = models.BooleanField(default=True, verbose_name='Статус')
    in_stock = models.BooleanField(default=True, verbose_name='Есть в наличии')
    featured = models.BooleanField(default=False, verbose_name='Рекомендуемый')
    digital = models.BooleanField(default=False, verbose_name='Цифровой')
    sku = ShortUUIDField(unique=True, length=4, max_length=10, verbose_name="UUID")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновление')

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def get_percentage(self):
        return (self.price / self.old_price) * 100

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    image = models.ImageField(upload_to='product-image', verbose_name='Изображения')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт', related_name='images')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Изображение продукта'
        verbose_name_plural = 'Изображения продуктов'


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    price = models.DecimalField(max_digits=9999999999, decimal_places=2, verbose_name='Цена')
    paid_status = models.BooleanField(default=False, verbose_name='Платный статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=10, default='process')

    class Meta:
        verbose_name = 'Корзина заказа'
        verbose_name_plural = 'Корзина заказов'


class CartOrderItem(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE, verbose_name='Заказ')
    product_status = models.CharField(max_length=200, verbose_name='Статус')
    item = models.CharField(max_length=200, verbose_name='Элемент')
    invoice_number = models.CharField(max_length=200, verbose_name='Номер счета')
    image = models.CharField(max_length=200, verbose_name='Изображения')
    quantity = models.IntegerField(default=0, verbose_name='Количество')
    price = models.DecimalField(max_digits=9999999999, decimal_places=2, verbose_name='Цена')
    total = models.DecimalField(max_digits=9999999999, decimal_places=2, verbose_name='Общий')

    class Meta:
        verbose_name = 'Товар заказа в корзине'
        verbose_name_plural = 'Товары для заказа в корзине'

    def order_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    review = models.TextField(verbose_name='Текст')
    rating = models.IntegerField(choices=RATING, default=None, verbose_name='Рейтинг')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Обзор продукта'
        verbose_name_plural = 'Обзоры продуктов'
        default_related_name = 'reviews'

    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.rating


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Список желаний'
        verbose_name_plural = 'Списки желаний'

    def __str__(self):
        return self.product.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    address = models.CharField(max_length=100, null=True, verbose_name='Адрес')
    status = models.BooleanField(default=False, verbose_name='Статус')

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

core/views.py
from django.shortcuts import render

from core.models import Product, Category, Vendor


def index(request):
    products = Product.objects.filter(featured=True, product_status='published')

    return render(request, 'core/home.html', {
        'products': products
    })


def product_list(request):
    products = Product.objects.filter(product_status='published')

    return render(request, 'core/products/list.html', {
        'products': products
    })


def categories_list(request):
    categories = Category.objects.all()

    return render(request, 'core/categories/list.html', {
        'categories': categories
    })


def category_product_list_view(request, cit):
    # dd(cit)
    category = Category.objects.get(cit=cit)
    products = Product.objects.filter(product_status='published', category=category)

    return render(request, 'core/categories/product-list.html', {
        'category': category,
        'products': products
    })


def vendor_list(request):
    vendors = Vendor.objects.all()

    return render(request, 'core/vendors/list.html', {
        'vendors': vendors
    })


def vendor_detail(request, vid):
    vendor = Vendor.objects.prefetch_related('products').get(vid=vid)
    return render(request, 'core/vendors/detail.html', {
        'vendor': vendor
    })

def product_detail(request, pid):
    product = Product.objects.get(pid=pid)
    related_products = Product.objects.filter(category=product.category_id).exclude(pid=pid)



    return render(request, 'core/products/detail.html', {
        'product': product,
        'related_products': related_products
    })

templates/core/vendors/list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
    <!--End header-->
    <main class="main pages mb-80">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Vendors List
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="archive-header-2 text-center">
                    <h1 class="display-2 mb-50">Список поставщиков</h1>
                    <div class="row">
                        <div class="col-lg-5 mx-auto">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Поиск поставщиков (по имени или ID)..."/>
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-50">
                    <div class="col-12 col-lg-8 mx-auto">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p>У нас сейчас <strong class="text-brand">{{ vendors.count }}</strong> поставщик</p>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Mall</a></li>
                                            <li><a href="#">Featured</a></li>
                                            <li><a href="#">Preferred</a></li>
                                            <li><a href="#">Total items</a></li>
                                            <li><a href="#">Avg. Rating</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row vendor-grid">
                    {% for vendor in vendors %}
                    	<div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            <div class="product-badges product-badges-position product-badges-mrg">
                                <span class="hot">Mall</span>
                            </div>
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="{% url 'core:vendor_detail' vendor.vid %}">
                                        <img class="default-img" src="{{ vendor.image.url }}"
                                             alt=""/>
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">{{ vendor.products.count }} продукт</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since 2012</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'core:vendor_detail' vendor.vid %}">{{ vendor.title }}</a></h4>

                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="{% static 'assets/imgs/theme/icons/icon-location.svg' %}"
                                                     alt=""/><strong>Address: </strong> <span>{{ vendor.address }}</span>
                                            </li>
                                            <li><img src="{% static 'assets/imgs/theme/icons/icon-contact.svg' %}"
                                                     alt=""/><strong>Call
                                                Us:</strong><span>{{ vendor.contact }}</span></li>
                                        </ul>
                                        <a href="{% url 'core:vendor_detail' vendor.vid %}" class="btn btn-xs">Visit Store <i
                                                class="fi-rs-arrow-small-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!--end vendor card-->
                </div>

                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">6</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>

{% endblock %}
<!--End header-->